server:
  port: 8081
  error:
    include-stacktrace: never
spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/fic_todo_app
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      max-lifetime: 300000
      idle-timeout: 290000
      connection-test-query: SELECT 1
      allow-pool-suspension: false
      maximum-pool-size: 30
      minimum-idle: 10
      connection-timeout: 300000
      validation-timeout: 150000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

